# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3.9-node-browsers
    working_directory: ~/repo
    steps: # a set of executable commands
      - checkout # special step to check out source code to working directory
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo docker-php-ext-install zip
      - run: sudo composer self-update
      - restore_cache: # special step to restore the dependency cache if `composer.lock` does not change
          keys:
            - composer-v2-{{ checksum "composer.json" }}
      - run: composer install -n --prefer-dist
      - run: cp .env.testing .env
      - run: touch storage/database.sqlite
      - run: php artisan cache:clear
      - run: php artisan migrate --env=testing --database=sqlite --force
      - save_cache: # special step to save the dependency cache with the `composer.lock` cache key template
          key: composer-v2-{{ checksum "composer.json" }}
          paths:
            - vendor
            - storage/database.sqlite
      - persist_to_workspace:
          root: ./
          paths:
            - ./
  unit_tests:
    docker:
      - image: circleci/php:7.3.9-node-browsers
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ./
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo docker-php-ext-install zip
      - run: sudo composer self-update
      - restore_cache: # special step to restore the dependency cache if `composer.lock` does not change
          keys:
            - composer-v2-{{ checksum "composer.json" }}
      - run: composer install -n --prefer-dist
      - run: ./vendor/bin/phpunit --testdox

workflows:
  CI-Test:
    jobs:
      - build
      - unit_tests:
          requires:
            - build
